### ISSUE TITLE
Dependency error for simple app

### ISSUE THREAD

**Issue by isuhendro** [bvaughn/react-presents#17]
First of all, `react-presents` is cool.

I am trying with simple presentation (code below), and getting `func of undefined` error.
Could you share any suggestion? Thanks.

```
TypeError: Cannot read property 'func' of undefined
./node_modules/react-codemirror/lib/Codemirror.js
node_modules/react-codemirror/lib/Codemirror.js:11
   8 | displayName: 'CodeMirror',
   9 | 
  10 | propTypes: {
> 11 | 	onChange: React.PropTypes.func,
  12 | 	onFocusChange: React.PropTypes.func,
  13 | 	options: React.PropTypes.object,
  14 | 	path: React.PropTypes.string,
```

```js
import React from 'react'
import { Presentation, Slide, DropDownNav } from 'react-presents'
import MySlide from './MySlide'

const slides = [MySlide, MySlide];

const options = slides
  .map((slide, index) => ({
    label: slide.title,
    value: index
  }))
  .filter((option) => option.label) 


export default () => (
  <Presentation>
    {slides.map((Component, index) => (
      <Slide
        component={Component}
        key={index}
      />
    )).concat(
      <DropDownNav
        key='DropDownNav'
        options={options}
      />
    )}
  </Presentation>
)
```

**Comment by bvaughn** [comment]
The error you're seeing is because `react` deprecated `React.PropTypes` in version 15.5 and removed them entirely in version 16.0. There is now a new, standalone [`prop-types`](https://www.npmjs.com/package/prop-types) module. You can read more about that decision [here](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes).

The error you've reported is coming from a _dependency_ of `react-presents` (and not `react-presents` itself). The dependency in question is `react-codemirror` (as your error message shows):
> TypeError: Cannot read property 'func' of undefined
./node_modules/react-codemirror/lib/Codemirror.js
node_modules/react-codemirror/lib/Codemirror.js

Currently, `react-presents` depends on `react-codemirror` version `^0.2.6`. It looks like there's a version `1.0.0` release. Based on the [peer dependency it declares](https://github.com/JedWatson/react-codemirror/blob/c3ae528465bcdc4f20780892f8a9111e785fa577/package.json#L32), it will warn about not being `react@16` compatible (see the warning below) but it _does_ use the `prop-types` package so it would fix the specific issue you reported.

> warning "react-codemirror@1.0.0" has incorrect peer dependency "react@>=15.5 <16".
warning "react-codemirror@1.0.0" has incorrect peer dependency "react-dom@>=15.5 <16".
warning "styled-components@1.4.6" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".

Based on issue JedWatson/react-codemirror/issues/126, it looks like [scniro/react-codemirror2](https://github.com/scniro/react-codemirror2) might be a drop-in replacement that's 16 compatible. I'm hesitant to make _that_ switch though.

I've release an update to `react-presents`, version **0.7.10**, that bumps the `react-codemirror` dependency to version 1.0.0. Based on my own quick testing with `react@16.0.0` it should resolve your issue. 👍

**Comment by isuhendro** [comment]
Many thanks @bvaughn for releasing new update very quickly 👍

**Comment by scniro** [comment]
@bvaughn @isuhendro I'd encourage you to migrate to [react-codemirror2](https://github.com/scniro/react-codemirror2). Jes'd `react-codemirror` seems long abandoned with a plethora of issues and many users frustrated. I wrote `react-codemirror2` as a successor and plan to actively maintain it moving forward.

**Comment by bvaughn** [comment]
@scniro if you'd like to create a PR that does the upgrade, and it seems to be a drop-in replacement, I'll review and consider. I don't think `react-presents` currently suffers from any of the unresolved `react-codemirror` issues though (other than lack of official v16 support).
