### ISSUE TITLE
Printing slides

### ISSUE THREAD

**Issue by dbendy** [bvaughn/react-presents#20]
Is there an easy way to print slides made with this library?

**Comment by bvaughn** [comment]
No, short of manually stepping through and printing each slide using the browser's built-in print functionality.

I'm not sure how you'd automatically print a summary view to be honest. Since a given slide can show and hide info as you step through it, just printing the end state of each slide might not suffice.

That being said, if you'd like to contribute a PR with some sort of print support, I'd be happy to review it.
